// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOr6iipm-PyvbBRyxrXaIQvwQO995idiU',
    appId: '1:978471232696:web:897e1916f25075ff55404d',
    messagingSenderId: '978471232696',
    projectId: 'testing-d9e98',
    authDomain: 'testing-d9e98.firebaseapp.com',
    databaseURL: 'https://testing-d9e98-default-rtdb.firebaseio.com',
    storageBucket: 'testing-d9e98.firebasestorage.app',
    measurementId: 'G-0D8V4MXFCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxP5t6kWq5T1uzF1KtJ5oUCw8k-ke9Ua0',
    appId: '1:978471232696:android:a1d8e4cfa643a6f755404d',
    messagingSenderId: '978471232696',
    projectId: 'testing-d9e98',
    databaseURL: 'https://testing-d9e98-default-rtdb.firebaseio.com',
    storageBucket: 'testing-d9e98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANqvKjQz0V7NMMu6XiEaZU33GXSEc1jTU',
    appId: '1:978471232696:ios:7c6d99c4ba8ee7bf55404d',
    messagingSenderId: '978471232696',
    projectId: 'testing-d9e98',
    databaseURL: 'https://testing-d9e98-default-rtdb.firebaseio.com',
    storageBucket: 'testing-d9e98.firebasestorage.app',
    iosClientId: '978471232696-oaj0kgt5a1isvj39r1l6nupb69gg4lb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANqvKjQz0V7NMMu6XiEaZU33GXSEc1jTU',
    appId: '1:978471232696:ios:7c6d99c4ba8ee7bf55404d',
    messagingSenderId: '978471232696',
    projectId: 'testing-d9e98',
    databaseURL: 'https://testing-d9e98-default-rtdb.firebaseio.com',
    storageBucket: 'testing-d9e98.firebasestorage.app',
    iosClientId: '978471232696-oaj0kgt5a1isvj39r1l6nupb69gg4lb5.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOr6iipm-PyvbBRyxrXaIQvwQO995idiU',
    appId: '1:978471232696:web:19a2fe38e132e55355404d',
    messagingSenderId: '978471232696',
    projectId: 'testing-d9e98',
    authDomain: 'testing-d9e98.firebaseapp.com',
    databaseURL: 'https://testing-d9e98-default-rtdb.firebaseio.com',
    storageBucket: 'testing-d9e98.firebasestorage.app',
    measurementId: 'G-VGVGNSZRJS',
  );

}